### PR TITLE
Update cico_setup script

### PR DESCRIPTION
**Pull request by GeetikaBatra**
Signed-off-by: Geetika Batra <gbatra@redhat.com

### CODE REVIEW

**Comment by msrb** [comment]
[test]

**Comment by GeetikaBatra** [comment]
[test]

**Comment by GeetikaBatra** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Pull request merged**
